apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-user-1
  namespace: user-1-namespace
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-nfs