apiVersion: v1
kind: Pod
metadata:
  name: user-2
  namespace: user-2-namespace
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu
    command:
      - "sleep"
      - "604800"
    volumeMounts:
    - mountPath: /my-nfs-share
      name: user-2
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
  volumes:
  - name: user-2
    persistentVolumeClaim:
      claimName: nfs-pvc-user-2
      readOnly: false
