apiVersion: v1
kind: Pod
metadata:
  name: user-1
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu
    command:
      - "sleep"
      - "604800"
    volumeMounts:
    - mountPath: /my-nfs-share
      name: user-1
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
  volumes:
  - name: user-1
    persistentVolumeClaim:
      claimName: nfs-pvc-user-1
      readonly: false
