apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-user-2
  namespace: user-2-namespace
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-nfs