apiVersion: crownlabs.polito.it/v1alpha2
kind: Template
metadata:
  name: filebrowser-template
  namespace: workspace-test
spec:
  prettyName: Filebrowser
  description: A template about Filebrowser
  environmentList:
    - name: filebrowser-environment
      environmentType: Standalone
      image: filebrowser/filebrowser:latest
      resources:
        cpu: 1
        memory: 500M
        reservedCPUPercentage: 1
      containerStartupOptions:
        startupArgs:
          - '--root=/media/nfs-share'
          - '--database=/tmp/database.db'
          - '--noauth=true'
          - '--baseurl=$(CROWNLABS_BASE_PATH)'
          - '--port=$(CROWNLABS_LISTEN_PORT)'
  workspace.crownlabs.polito.it/WorkspaceRef:
    name: test
  deleteAfter: 1h
